# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

build site:
  image: registry.gitlab.com/yawik/docker/yarn-git-ssh-rsync:main
  stage: build
  script:
    - env | grep -E "(PORT|APP_ID|EMAIL|YAWIK|STRAPI|GOOGLE|HEADER)" > .env.production
    - yarn
    - yarn build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

stages:
  - build
  - deploy

deploy_master:
  stage: deploy
  image: registry.gitlab.com/yawik/docker/yarn-git-ssh-rsync:main
  environment:
    name: staging/$CI_COMMIT_REF_NAME
    url: https://cross-solution.de
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  only:
    - main
  script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - echo "$SSH_SERVER_HOSTKEYS" > ~/.ssh/known_hosts
    - rsync -ra --exclude=node_modules --exclude=frankfurt-im-nebel.jpg --delete dist/ssr/ nuxt@cross-solution.de:/srv/cross-solution/ssr/
    - ssh nuxt@cross-solution.de sudo /bin/systemctl restart nodeserver-quasar.service
  resource_group: production


